version: '3.9'
# Общая сеть для всех контейнеров
networks:
  service_network:
services:
  # Образ и версия базы, которую мы будем использовать
  db:
    image: postgres:latest
    networks:
      service_network:
    # Перезапускаем все остановленные и работающие службы
    restart: always
    container_name: postgres
    # Внешний том(volume) и место где он будет подключен внутри контейнера
    volumes:
      - postgres_volume:/var/lib/postgresql/data/
    # Учетные данные
    env_file:
      - ./.env
      # Открываем порт 5432 внутри и снаружи
    ports:
      - "5432-5432"

#  service_employee:
#    # Берем Dockerfile из каталога product_sevice
#    build:
#      context: ./service_employee
#    networks:
#      service_network:
#    # Внешний том(volume) и место где он будет подключен внутри контейнера
#    # и статика внутри контейнера
#    volumes:
#      - ./service_employee/:/app
##      - static_volume:/app/static
##      - media_volume:/app/media
#    # Перезапускаем все остановленные и работающие службы
#    restart: always
#    # Открываем порт 8000 внутри и снаружи 8001
#    ports:
#      - "8000:8000"
#    # Переменные окружения
#    env_file:
#      - ./.env
#    # Запускаем сначала postgres
#    depends_on:
#      - db
volumes:
  postgres_volume: